import { chromium } from 'file:///C:/Users/Huo%20Hengyuan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const password = (await fs.readFile('.env.local', 'utf8')).match(/^ADMIN_PASSWORD=(.+)$/m)[1];
const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(100000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('dialog', d => d.accept());
const base = 'http://127.0.0.1:4191';
const shots = `D:/hhy/agent-framework/edulab/classroom-web/data/runner-check-${Date.now()}`;
await fs.mkdir(shots, { recursive: true });
try {
  await context.request.post(base + '/api/classroom/login', { headers: { Origin: base }, data: { kind: 'admin', password } });
  const created = await (await context.request.post(base + '/api/classroom/admin/students', { headers: { Origin: base }, data: { group: 'A', count: 1 } })).json();
  await context.request.post(base + '/api/classroom/logout', { headers: { Origin: base }, data: {} });
  await page.goto(base);
  await page.locator('#credential').fill(created.students[0].code);
  await page.locator('#login-button').click();
  await page.locator('#run-python').waitFor();
  async function run(code, input = '') {
    await page.locator('#code').fill(code);
    if (!await page.locator('#python-stdin').isVisible()) await page.locator('.stdin-panel summary').click();
    await page.locator('#python-stdin').fill(input);
    await page.locator('#run-python').click();
    await page.waitForFunction(() => !document.querySelector('#run-python').disabled, { timeout: 100000 });
    const status = await page.locator('#run-status').textContent();
    const output = await page.locator('#python-output').textContent();
    if (/加载失败/.test(status)) throw new Error(status + ': ' + output);
    return { status, output };
  }
  let r = await run('print("你好，Python")\nprint(12 * 2.5)');
  assert.equal(r.status, '运行完成'); assert.match(r.output, /你好，Python\n30.0/);
  console.log('PASS real Python output');
  r = await run('count = int(input("数量："))\nmass = float(input("质量："))\nprint(count * mass)', '12\n2.5');
  assert.equal(r.status, '运行完成'); assert.match(r.output, /30.0/);
  r = await run('total = 0\nfor _ in range(5):\n    total += int(input())\nprint(total)', '10\n12\n8\n15\n5');
  assert.match(r.output, /50/); assert.equal(r.status, '运行完成');
  r = await run('total = 0\nx = int(input())\nwhile x != -1:\n    total += x\n    x = int(input())\nprint(total)', '10\n12\n-1');
  assert.match(r.output, /22/);
  r = await run('def valid(x):\n    return 20 <= x <= 25\nprint(sum(valid(x) for x in [18,20,23,25,27]))');
  assert.equal(r.output.trim(), '3');
  console.log('PASS input, for, while, functions');
  r = await run('input()'); assert.match(r.output, /EOFError/); assert.match(r.output, /输入不足/);
  r = await run('print(1 / 0)'); assert.match(r.output, /ZeroDivisionError/); assert.equal(r.status, '运行出错');
  r = await run('if True\n    print(1)'); assert.match(r.output, /SyntaxError/);
  await page.locator('#ask-code').click();
  await page.locator('.turn .answer').waitFor();
  assert.match(await page.locator('.question').last().textContent(), /SyntaxError/);
  await page.locator('#code').fill('print("changed")');
  assert.match(await page.locator('#run-status').textContent(), /已修改/);
  await page.locator('#ask-code').click();
  await page.waitForFunction(() => document.querySelectorAll('.turn').length === 2 && !document.querySelector('#send').disabled);
  assert.match(await page.locator('.question').last().textContent(), /尚无匹配的运行结果/);
  assert.doesNotMatch(await page.locator('.question').last().textContent(), /SyntaxError/);
  console.log('PASS errors and one-click context without stale output');
  await page.locator('#code').fill('while True:\n    pass');
  await page.locator('#run-python').click();
  await page.waitForFunction(() => document.querySelector('#run-status').textContent === '正在运行…');
  await page.locator('#stop-python').click();
  assert.equal(await page.locator('#run-status').textContent(), '已停止');
  r = await run('while True:\n    pass'); assert.match(r.status, /超过 10 秒/);
  r = await run('print("x" * 30000)'); assert.ok(r.output.length < 17000); assert.match(r.output, /已截断/);
  r = await run('print("恢复正常")'); assert.equal(r.output.trim(), '恢复正常');
  await page.screenshot({ path: shots + '/desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#show-code').click();
  await page.locator('#run-python').scrollIntoViewIfNeeded();
  await page.screenshot({ path: shots + '/mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  console.log('PASS stop, timeout, truncation, recovery, mobile');
  await context.route('**/python-runtime/**', route => route.abort());
  await page.locator('#run-python').click();
  await page.waitForFunction(() => !document.querySelector('#run-python').disabled);
  assert.match(await page.locator('#run-status').textContent(), /加载失败/);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ ok: true, screenshots: shots }));
} finally { await context.close(); await browser.close(); }
